class HomeStrings {
  const HomeStrings._();

  static const String journeyStart = 'Your journey starts here';
  static const String joinCreators = 'Join 2,000+ creators building the future.';
  static String hiGreeting({required String name}) => 'Hi, $name 👋';
  static const String greetingSubtitle = "Let's build something great today";
  static const String tipBanner = 'Tip: Join a team to start building real projects';
  static const String basedOnCompleted = 'Based on completed tasks';
  static const String projectProgress = 'Project Progress';
  static const String projectProgressSubtitle = 'Track your contribution across projects.';
  static const String focusOnImpact = 'Focus on Impact';
  static const String focusOnImpactDescription = 'Your efficiency has increased by 12% this month.';
  static const String aiInsights = 'AI Insights';
  static const String insightProductivity = 'You completed 30% more tasks this week compared to your average.';
  static const String insightPeakTime = 'You are most productive in the evening (6 PM - 9 PM).';
  static const String home = 'Home';
  static const String chat = 'Chat';
  static const String projects = 'Projects';
  static const String profile = 'Profile';
  static const String notifications = 'Notifications';
  static const String markAllRead = 'Mark all as read';
  static const String reload = 'Reload';
  static const String search = 'Search teams or messages...';
  static const String chats = 'Chats';
  static const String viewAll = 'View All';
  static const String details = 'Details';
  static const String cancel = 'Cancel';
  static const String confirm = 'Confirm';
  static const String edit = 'Edit';
  static const String saveChanges = 'Save Changes';
  static const String addSkill = 'Add Skill';
  static const String logout = 'Log Out';
  static const String logoutTitle = 'Log out of Bridge X?';
  static const String logoutConfirm = 'Are you sure you want to sign out? You will need to log back in to access your projects.';

  // ── Productivity ──────────────────────────────────────────────────────────
  static const String yourProductivity = 'Your Productivity';
  static const String totalTasks = 'Total Tasks';
  static const String completedProjects = 'Projects Completed';
  static const String activeMembers = 'Active Members';
  static const String totalDone = 'Total Done';
  static const String thisWeek = 'This Week';
  static const String recentlyFinished = 'Recently Finished';
  static const String goalSmashed = 'Goal Smashed!';
  static const String goalSmashedDesc = "You've completed 20% more tasks this month than the previous one. Keep the momentum";
  static const String viewInsights = 'View Insights';
  static const String viewReport = 'View Report';
  static const String submitReport = 'Submit Report';
  static const String reportUser = 'Report User';
  static const String makeMentor = 'Make Mentor';
  static const String selectAReason = 'SELECT A REASON';
  static const String notContributing = 'Not contributing';
  static const String missedDeadlines = 'Missed deadlines';
  static const String inappropriateBehavior = 'Inappropriate behavior';
  static const String spamOrIrrelevantMessages = 'Spam or irrelevant messages';
  static const String other = 'Other';
  static const String describeTheIssue = 'Describe the issue...';
  static const String reportSubmittedSuccess = 'Report submitted successfully';
  static const String failedToLoadUser = 'Failed to Load User';
  static const String submitReportTitle = 'Submit report?';
  static const String submitReportDesc = 'Are you sure you want to report this user? Our team will review the activity promptly.';
  static const String reportSubmittedDesc = 'Our team will review your report to build trust and clarity. Thank you for helping us maintain a healthy collaboration environment.';
}
