// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdAJ2FS6cyuZFLSHmJj2ZEXkyKObp1u0',
    appId: '1:827671253011:web:ad633f1ed6524200546fe6',
    messagingSenderId: '827671253011',
    projectId: 'bridgex-81714',
    authDomain: 'bridgex-81714.firebaseapp.com',
    storageBucket: 'bridgex-81714.firebasestorage.app',
    measurementId: 'G-RB9BXZXQCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIKQJkgwYVQEK0WKLAIl4BlAxGCMJ5JgM',
    appId: '1:827671253011:android:1c05a61bc13efcb5546fe6',
    messagingSenderId: '827671253011',
    projectId: 'bridgex-81714',
    storageBucket: 'bridgex-81714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcUTZkaQ2lPCB5IoxivmQgVc17U1nE9X4',
    appId: '1:827671253011:ios:4dea3fced8a8061b546fe6',
    messagingSenderId: '827671253011',
    projectId: 'bridgex-81714',
    storageBucket: 'bridgex-81714.firebasestorage.app',
    iosBundleId: 'com.example.bridgex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcUTZkaQ2lPCB5IoxivmQgVc17U1nE9X4',
    appId: '1:827671253011:ios:4dea3fced8a8061b546fe6',
    messagingSenderId: '827671253011',
    projectId: 'bridgex-81714',
    storageBucket: 'bridgex-81714.firebasestorage.app',
    iosBundleId: 'com.example.bridgex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvdAJ2FS6cyuZFLSHmJj2ZEXkyKObp1u0',
    appId: '1:827671253011:web:45a7e6ace6c71916546fe6',
    messagingSenderId: '827671253011',
    projectId: 'bridgex-81714',
    authDomain: 'bridgex-81714.firebaseapp.com',
    storageBucket: 'bridgex-81714.firebasestorage.app',
    measurementId: 'G-C7HH94JK78',
  );
}
